spring.application.name=giraffe-api

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/giraffe_db
spring.datasource.username=postgres
spring.datasource.password=9378

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
